# Generated by Django 3.2.13 on 2022-06-09 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_remove_product_stock_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.FloatField(null=True),
        ),
    ]
