# Generated by Django 3.2.13 on 2022-06-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_order_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='DoB',
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
