# Generated by Django 3.2.13 on 2022-06-10 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_remove_order_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_pdt_TTC',
        ),
        migrations.AddField(
            model_name='customer',
            name='dob',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('en préparation', 'en préparation'), ('expédié', 'expédié'), ('livré', 'livré'), ('retour client', 'retour client')], default='en préparation', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Informatique', 'Informatique'), ('Téléphonie', 'Téléphonie'), ('Objets connectés', 'Objets connectés'), ('TV & Home cinéma', 'TV & Home cinéma')], max_length=200, null=True),
        ),
    ]
