# Generated by Django 3.2.13 on 2022-06-10 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_auto_20220610_0536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('Operator', models.CharField(max_length=255, null=True)),
                ('Type', models.CharField(choices=[('erreur prix', 'erreur prix'), ('article erronné', 'article erronné'), ('article defectueux', 'article defectueux')], max_length=255, null=True)),
                ('action', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(choices=[('ouverte', 'ouverte'), ('résolue', 'résolue')], default='ouverte', max_length=255, null=True)),
                ('resolution_date_expected', models.DateTimeField(null=True)),
                ('last_contact_customer_date', models.DateTimeField(blank=True, null=True)),
                ('resolution_date_final', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.customer')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.order')),
            ],
        ),
    ]
