# Generated by Django 3.2.13 on 2022-06-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0015_alter_claim_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='Delivery_date_expected',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='Delivery_date_final',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
