# Generated by Django 3.2.13 on 2022-06-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0016_auto_20220610_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateTimeField(null=True),
        ),
    ]
