# Generated by Django 3.2.13 on 2022-06-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0020_auto_20220611_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='satisfaction_score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
