# Generated by Django 3.2.13 on 2022-06-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0021_alter_order_satisfaction_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='satisfaction_score',
            field=models.FloatField(default=0, null=True),
        ),
    ]
