# Generated by Django 3.2.13 on 2022-06-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0023_auto_20220611_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketing',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='satisfaction_score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('en préparation', 'en préparation'), ('expédié', 'expédié'), ('livré', 'livré')], default='livré', max_length=255, null=True),
        ),
    ]
