# Generated by Django 3.2.13 on 2022-06-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0024_auto_20220611_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='Operator',
            field=models.CharField(choices=[('Amani', 'Amani'), ('Harley', 'Harley'), ('Robin', 'Robin')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='satisfaction_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
