# Generated by Django 3.2.13 on 2022-06-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0025_auto_20220613_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='action',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='description',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='description',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
