# Generated by Django 3.2.13 on 2022-06-14 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0026_auto_20220614_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketing',
            name='customer_segment',
            field=models.CharField(choices=[('Stars', 'Stars'), ('Nouvelle inscription', 'Nouvelle inscription'), ('Potentiel moyen', 'Potentiel moyen')], max_length=255, null=True),
        ),
    ]
