# Generated by Django 3.2.13 on 2022-06-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0027_alter_marketing_customer_segment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='resolution_date_expected',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='Delivery_date_expected',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
